name: Lint,Test,Deploy app in three job
on: [push,workflow_dispatch ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: setup the nodejs
        uses: actions/setup-node@v4
        with:
            node-version: "18.x"
      - name: Install Dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint 

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: setup the nodejs
        uses: actions/setup-node@v4
        with:
            node-version: "18.x"
      - name: Install Dependencies
        run: npm ci        
      - name: Test the code
        run: npm run test

  deploy:
    needs: [lint,test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: setup the nodejs
        uses: actions/setup-node@v4
        with:
            node-version: "18.x"
      - name: Install Dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Deploy the code
        run: echo "Deploying..."
      