name: test
on:
 workflow_dispatch:

jobs:
  test:
    name: Select Environment
    runs-on: ubuntu-latest
    steps:
      - run: |
          az version
          az extension add --name datafactory
      - run: |
          az upgrade -y
