name: "Z - file"
on: [push,workflow_dispatch ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: setup the nodejs
        uses: actions/setup-node@v4
        with:
            node-version: "18.x"
      - name: Install Dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint 
      - name: Test the code
        run: npm run test
      - name: Build the code
        run: npm run build
      - name: Deploy the code
        run: echo "Deploying..."
      